project:
  type: website

website:
  title: "Syke in LPS25"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - syke.scss
    css: styles.css
    toc: true



