---
title: "Finnish Environment Institute (Syke) in Living Planet Symposium 2025"
toc: True
self-contained: False
lightbox: 
  match: auto
  effect: zoom
  desc-position: bottom
  loop: true
format:
  html:
    smooth-scroll: true
---

Finnish Environment Insitute (Syke) has four presentations and seven posters in [Living Planet Symposium 2025](lps25.esa.int), along with several presentations and posters with Syke as a partner.

## Monday 23.6.2025

### State of play for Earth Observation tools to support Water Framework Directive (WFD)

**Jenni Attila¹**, Ioanna Varkitizi², Krista Alikas³, Sandra Poikane², Gary Free², Wouter van de Bund²

Affiliations: ¹Finnish Environment Institute (Syke) ²Joint Research Centre ³University of Tartu

* What: Presentation
* Session: [F.04.05 In-land Water Quality and Resources Management - PART 1](https://lps25.esa.int/programme/programme-session/?id=C7E7042E-382E-4023-8E32-EF5B5E589981)
* Room: Room 0.11/0.12
* Time: 14:00

::: {.callout appearance="default" collapse=true}

#### Show abstract

In 2024, Joint Research Centre initiated a survey to map the use of Earth observations (EO), and specifically satellite observations, in the Water Framework Directive (WFD) in each EU Member State (MS). In addition, the survey welcomed answers about actions in using EO in water quality status assessment in some European countries that are not EU MS. The aim of the survey was to explore with the Member States and EO experts, how EO tools could better serve and support their needs for WFD purposes. Also the survey was targeted to make preparations for the ECOSTAT work programme 2025-2027, where one of the tasks is dedicated to advancing the use of EO for WFD (Exploitation of remote sensing data in WFD monitoring and classification). 

The survey mapped four specific topics with altogether 18 questions: Present use of EO for WFD in MS, Strengths and limitations of EO data in the WFD monitoring and assessment, Willingness of MS to increase the use of EO, and WG ECOSTAT future work. 

The survey was sent to EO experts and their colleagues of each MS during Aug-Sep 2024. It was also shared for Copernicus User Forum national representatives. As a result, 45 answers were received from altogether 22 MS. Most of the answers were given by EO experts (66%) and national Copernicus user forum representatives (14%). Out of the present use of EO to support WFD, most focus is put on lakes and coastal water types (68% each), but also rivers and transitional water types have cases where EO is used for the purposes of WFD status assessment. 

According to the survey, in most EU countries, EO data are presently not yet used as part of WFD status assessment - although there are very good results on how EO can support WFD. However, there are some exceptions to this, for example Finland, Belgium and Sweden already utilize EO data in WFD reporting. Most often EO data are produced by national public entities, private companies, Copernicus services and Lakes/Ocean Color CCI. Among the EO data that are used in different water categories (rivers, lakes, coastal and transitional waters), most often EO is used to derive Chlorophyll-a, turbidity and total suspended matter. Harmful Algal Blooms (HABs) and surface temperature follow, while deriving water color and Secchi depth and mapping of hydromorphological modifications come next. In the countries where EO is used for status assessment, EO is used as supporting information via so-called expert judgement rule or via modelling. Typically, EO is used as water body-specific results and indicators. 

The main benefits of the present use of EO data in WFD monitoring were clear: more than 80% of the respondents felt that increase in spatial coverage, availability of EO over water bodies with no sampling and cost-effectiveness are all relevant benefits. Furthermore, there is clear trust in that EO can also increase the confidence of status assessment in the future. 

The survey also mapped, which are the major obstacles for taking EO as one monitoring method to account in WFD. Three major obstacles were ranked high: 1. there are no common guidelines on how to utilize EO for WFD reporting, 2. there are legal issues in WFD (use of EO is seen against current WFD monitoring guidelines) and 3. authorities are not well informed about EO datasets and tools. Other relevant obstacles categorized as ‘obstacles to some extent’ were related to technical linkages between EO data and WFD assessment, such as lack of interfaces for EO data or WFD assessment systems are not suitable for EO data. Furthermore, the respondents identified the following two given ‘obstacles to some extent’ related to EO data and its quality most often: EO depends too much on meteorological conditions, or that only few WFD parameters can be measured via EO. Also the fact that EO cannot trace deep chl-a maxima in open ocean or may result in overestimations over turbid or humic waters (near coast and in river estuaries) or that EO resolution was not considered good enough for small lakes were also raised up in the answers. 

In most EU countries, the willingness to increase the use of EO for WFD is high. There are very good results on how EO can support WFD, and preparations are being made for the future use. Actions to prepare the future use of EO for WFD are most related to research and development (field data collection, validation, algorithm development and creation of quality control procedures and uncertainty estimation). Also, numerous user uptake actions are being made, like workshops, training and other events, where EO experts and authorities share information. Some web applications exist, that provide EO water quality to either WFD status assessment or promote the use of EO for water quality in management in general for national purposes. Such applications are e.g. System Saltbaltyk in Poland, Terrascope by Vito (viewer.terrascope.be), Finnish Tarkka (tarkka.syke.fi) by the Finnish Environment Institute, Estonian user interface by University of Tartu (https://fpcup.to.ee), EOapp Aqua by EOMAP (https://aqua.eoapp.de/) and two platforms by Brockmann Consult and Brockmann Geomatics (https://viewer.cyanoalert.com/ and (https://bc-viewer.brockmann-consult.de/). 

In most MS, there is willingness to use EO for WFD in the future, but not yet clear plan how to proceed. The survey mapped, what could be done to advance the use of EO in WFD status assessment. Most given alternatives for actions were seen rather beneficial, but the following four were ranked highest: 1. Adjustment of national water management systems: EO datasets should be integrated in national status assessment tool, 2. Training courses at national level, 3. User-friendly guidance and 4. Collaboration and discussion among MS. According to the respondents, EO is seen very useful for the harmonization of WFD with other EU Directives, mostly with Marine Strategy Framework Directive (MSFD), Bathing Directive (BD) and Habitats Directive (HD). In this presentation, we give an overview of the results of the survey and give information about the progress and plans about the actions in the next three years in ECOSTAT work.

:::

## Tuesday 24.6.2025

### European Biodiversity Partnership (Biodiversa+) harmonizing trans-national long-term biodiversity monitoring

**Petteri Vihervaara¹**, Toke Hoye, Michele Bresadola, Aino Lipsanen, Iiris Kallajoki, Cécile Mandon, Julia Seeber, Jamie Alison, Helene Blasbichler, Risto Heikkinen, Sara Wiman, Gaëlle Legras, Pierre Thiriet, Mathieu Basille, Mona Naeslund, Michelle Silva del Pozo, Alberto Basset, Senem Onen Tarantini, Martina Pulieri, Lluís Brotons, Gloria Casabella, Magdalena Henry, Constantinos Phanis, Rob Hendriks, Guillaume Body, Sophie Germann, Ron Winkler

* What: Poster
* Session: [A.02.02 - Terrestrial and Freshwater Biodiversity](https://lps25.esa.int/programme/programme-session/?id=472D3E0A-EBF2-4748-BAEA-CC2FDCF34239)
* Where: L09

::: {.callout appearance="default" collapse=true}

#### Show abstract

European Biodiversity Partnership (Biodiversa+) has been supporting transnational long-term biodiversity monitoring across Europe. Biodiversa+ was launched October 2021 and will last until October 2028. We will summarize the key achievements of the first years of cooperation (years 2021-2025) on biodiversity monitoring of over 20 countries participating in these activities. To support harmonization of biodiversity monitoring schemes, we have started six pilot projects that will test novel monitoring methods, such as remote sensing, environmental DNA, and automated sound and image recognition to improve biodiversity monitoring, and to provide deeper understanding of possibilities and challenges of extending them to true long-term monitoring schemes. Currently, we have been piloting monitoring of i) invasive alien species, ii) soil biodiversity, iii) moths, bats, and birds, iv) rocky-reef fish, and 5) grassland and wetland habitats. In addition, in the sixth pilot, we have been assessing governance aspects of national biodiversity monitoring coordination in ten countries. The budget of these pilots has been 8.3M€ so far, and 19 participating organisations from 18 countries have participated in the pilots. Besides of concrete collection of monitoring data, we have also developed transversal activities such as data management and interoperability as well as integrating the observational data into decision-making which has been demonstrated also. As part of implementation of novel monitoring methods, a roadmap for utilization of those novel methods have been conducted. We have also studied current funding spent on biodiversity monitoring as well as expected costs of upscaling piloted monitoring schemes to become true long-term monitoring programmes. We will highlight possibilities and challenges learned from these pilots. One of the main benefits of such transnational monitoring schemes is that they can provide calibration and validation data for Earth Observation biodiversity data products and remotely sensed data sets. Finally, possibilities to integrate in situ observations with remote sensing approaches will be discussed. We will also present a vision for the forthcoming biodiversity monitoring cooperation with Biodiversa+ and other key monitoring initiatives.

::: 

### Using Satellite Data to Assess Sensitive Habitats and the Pressures They Face

**Eeva Bruun¹**, Lauri Niskanen², Aleksi Nummelin³, Jenni Attila¹, Olli Malve¹, Elina Miettunen¹, Janne Mäyrä¹, Mikko Kervinen¹, Eero Alkio¹, Tomi Heilala¹, Markus Kankainen², Mika Laakkonen², Antti Westerlund³

Affiliations: 

* What: Poster
* Session: [A.08.07 - Ocean Health including marine and coastal biodiversity](https://lps25.esa.int/programme/programme-session/?id=D0B6689A-3D89-4950-93C1-CB477ADCB915)
* Where: I20

::: {.callout appearance="default" collapse=true}

#### Show abstract

Satellite observations can reliably assess the state of the environment, its temporal and spatial variations, and the characteristics of marine areas. Typically, satellite observations are used to describe variables related to eutrophication, such as the water's chlorophyll-a content, Secchi depth, and turbidity. In this study we assess the usefulness of satellite observations for evaluating the impacts of fish farming, and marine heat waves on marine habitats in the coastal waters of Finland (Baltic Sea). Additionally, Syke is developing methods to identify small boats from satellite observations, which will be used to assess the pressure small boats exert on marine areas annually. We do this by comparing satellite data with regionally comprehensive flow-through data measured from moving vessels, and point-wise laboratory samples from three marine areas along the Finnish coast. We utilize open-source Copernicus and NASA data and evaluate the benefits of commercial Very High Resolution (VHR) images in the areas of field measurement sites. VHR images provide more detailed satellite data closer to the shore, where open-source data cannot be utilized. The cost-benefits and reliability of the information obtained through satellite observations are evaluated. We also assess the usefulness of satellite sea surface temperature (SST) data in monitoring marine heat waves in sensitive habitats. For this we use observations from Sentinel-3 SLSTR and Landsat-8/9 TIRS and TIRS-2. TIRS instruments provide data at sub-kilometer resolution which is particularly important in shallow and complex coastal areas. Additionally, the Finnish Coastal Nutrient Load Model (FICOS) is used to assess how nutrient concentrations change in sensitive areas under different hydrodynamic and environmental conditions. The project is being carried out in collaboration with the Finnish Environment Institute (Syke), the Natural Resources Institute Finland (Luke), and the Finnish Meteorological Institute (FMI). The project started in the summer of 2024 and the study will be completed by the end of 2025. Co-funded by the European Union.

:::

## Wednesday 25.6.2025

### Water management in Finland: Open EO-service providing status assessment of marine and lake water quality

**Jenni Attila¹**, Hanna Alasalmi¹, Vesa Keto¹, Sakari Väkevä¹, Jesse Anttila¹, Eero Alkio¹, Sampsa Koponen¹, Mikko Kervinen¹, Eeva Bruun¹

Affiliations: ¹Finnish Environment Institute (Syke)

* What: Presentation
* Session: [F.05.01 Satellite EO data benefit the economy, the environment and our societies: the evidence and the stories](https://lps25.esa.int/programme/programme-session/?id=C8D79C4D-EB05-4559-A625-5CE4D1E86816)
* Room: Room 0.49/0.50
* Time: 16:15

::: {.callout appearance="default" collapse=true}

#### Show abstract

The requirements set for defining the status of water areas, for example, European Union Water Framework Directive (WFD), Marine Strategy Framework Directive (MSFD), and Habitat directive (HD), share common core elements with respect to status assessments. The status assessment is done using discrete classes for water bodies, sub-areas or critical sites representative for certain area of interest. For HD over marine areas it is marine habitats, such as lagoons and small narrow bays, whereas in WFD and MSFD it is coastal water bodies. Typically, chlorophyll a (chl-a), turbidity, and surface temperature belong to the main variables considered. In addition, nutrients such as total phosphorus, and transparency of the water, usually determined as Secchi disk depth, are accounted. 

During 2024, the 4th WFD reporting has been underway in EU Member States (MS). In Finland, the obligations set by EU for WFD reporting are high, and concern about 4600 lakes and more than 270 coastal water bodies with often an irregular shape and multitude of islands. Most of these water areas represent a large range of optically complex waters - absorption dominated humic waters that form one extreme part of Case II waters (aCDOM at wavelength 400 nm ranges between 0.1 and 29 m−1 and even higher over humic-rich lake water bodies). Tarkka web application (tarkka.syke.fi) by the Finnish Environment Institute is used to provide them together with the station sampling data collected within the reporting unit, water body. In addition to authorities responsible for status assessment, the service is open for public, which has made it popular among citizens and media. What makes it interesting for public is that the service provides a comprehensive archive of true color images over the area of Baltic Sea and its drainage basin. 

According to a recent ‘Sentinel benefits for society’-story (EARSC, 2022) ‘Using satellite data is especially helpful in a country like Finland where the large amount of water bodies would imply enormous associated costs for authorities should they have to use traditional monitoring methods across the whole country. Sentinel data therefore helps authorities to improve water quality at a lower cost, which in turn improves the quality of life for citizens, aids in the protection of biodiversity and helps to ensure environmental sustainability’. 

The primary users and tiers of Tarkka-service are the regional environmental centres and Syke. Furthermore, Ministries of Environment and of Agriculture and Forestry obtain strong regulatory benefits as they have access to better information - more comprehensive reports and data from SYKE and the regional centres - on which to base new policy decisions (EARSC, 2022). WFD status assessment in Finland has utilized EO chl-a for three rounds already: first time for the 2nd classification period in 2012 over coastal waters (Attila et al. 2018). During the 3rd classification round Copernicus Sentinel-2 MSI instrument-derived chl-a was utilized over most of the 250 coastal and over 2000 lake water bodies. For the 4th WFD period, we will increase the use of EO-based information in status assessment by increasing the availability of EO data over approximately 800 new lake water bodies and including satellite-based observations of total phosphorus over the south-west archipelago and certain nutrient-rich Finnish lakes. The satellite instruments used are Sentinel2 A&B MSI, Landsat 8&9 OLI, and Sentinel-3 OLCI. The water quality parameters provided are chl-a, turbidity, Secchi depth and surface temperature. For the forthcoming 4th WFD reporting, EO data and a separate analysis-part of Tarkka-service is linked directly to the national water management system used by the authorities responsible for status assessment. EO is accounted in WFD assessment via modelling. 

The backbone of Tarkka-service is STATUS database contains EO-based water quality information for regional authorities responsible for the WFD assessment. The STATUS database is used to store water body based daily statistics of EO water quality (chl-a, turbidity, surface temperature). Time series of observations, starting from 2013, are maintained via automated daily processing, including interfaces for following the data flow and, if needed, quality assurance by the operator. 

In this presentation we will give an overview of the solutions made to integrate EO to national water management, directive reporting and status assessment purposes. Also, we shortly overview cross-comparisons between the EO chl-a and monitoring site observations show good correlation over various water types and the correspondence between EO and station sampling based WFD status assessment of over 3000 lakes and 260 coastal water bodies in Finland. In our presentation the focus will be on environmental, regulatory, innovational, science & technology as well as societal benefits by the web application that serves on average 300 individual users daily. Although Tarkka was developed as authorities in mind, citizens and society benefit the economic, societal and environmental impacts of the service. 

References: 

* (EARSC, 2022). Sentinel benefits for the society- Water management in Finland, [https://earsc.org/sebs/wp-content/uploads/2022/11/Water-quality-in-Finland-Final.pdf](https://earsc.org/sebs/wp-content/uploads/2022/11/Water-quality-in-Finland-Final.pdf)
* Attila, J., Kauppila, P., Alasalmi, H., Kallio, K. K., Keto, V., Bruun, E. (2018). Applicability of Earth Observation chlorophyll a data in assessment of water status via MERIS with implications for the use of OLCI sensors. Remote Sensing of Environment, 212, 273 287. [https://doi.org/10.1016/j.rse.2018.02.043](https://doi.org/10.1016/j.rse.2018.02.043)

:::

### Integrating Earth Observation and Modelling for Carbon Budgeting in Finnish Boreal Lakes

**Sakari Väkevä¹**, Marie Korppoo¹, Minna Kuoppala¹, Jenni Attila¹, Marko Järvinen¹, Markus Huttunen¹, Pirkko Kortelainen¹, Karoliina Koho² and the Blue Lakes working group¹²³

Affiliations: ¹Finnish Environment Institute (Syke) ²Geological Survey of Finland (GTK) ³Department of Geosciences and Geography, University of Helsinki (UH)

* What: Poster
* Session: [B.02.05 - Restoring Biosphere Resilience: Transforming Agriculture, Forestry and Other Land Use (AFOLU) from Carbon Source to Sink](https://lps25.esa.int/programme/programme-session/?id=55635FDB-1BD7-496F-97AF-1CC0AC1F3F96)
* Where: R08

::: {.callout appearance="default" collapse=true}

#### Show abstract

The boreal lakes of Finland are accumulating allochthonous carbon. This is often linked to drainage from specific soil types and land use classes, particularly peatlands ditched for forestry or agriculture. Successive lakes within river networks retain transported organic carbon in bottom sediments through processes such as phytoplankton settling, flocculation, or direct sedimentation of organic particulates, or release it into the atmosphere as greenhouse gases (GHGs), such as methane and carbon dioxide. Lakes also contribute to carbon cycling through macrophyte production (blue carbon) and other related geochemical processes. In Finnish lakes, blue carbon is predominantly associated with helophytes such as the common reed (Phragmites australis), which exhibit significant above-surface biomass and are often accompanied by thick organic sediment beds. 

While nitrogen and phosphorus cycling are well-documented due to extensive research, regulatory frameworks, and cross-border initiatives, carbon cycling in boreal lakes remains less understood and has lacked an established accounting scheme. The 2019 wetlands refinement to the Intergovernmental Panel on Climate Change (IPCC) Guidelines for National GHG Inventories suggested that regulated natural lakes (where surface area and/or residence time are changed by >10 per cent) should be treated as reservoirs from the point of view of GHG reporting. In a country like Finland with numerous boreal lakes (57,000 of more than one hectare in size) and a long history of lake regulation, this can constitute a significant monitoring and reporting challenge. Recently, water ecosystem management has also gained attention as a tool to support national climate targets, raising expectations for increasing carbon storage by sustainable blue carbon utilization. 

The Blue Lakes project (2023–2025) aims to quantify carbon stock magnitudes, cycling and burial in three Finnish pilot lakes—Oulujärvi, Vesijärvi, and Kallavesi—and scale these findings nationally using field data, existing environmental databases, catchment-level modelling, and Earth Observation (EO). The lakes were visited in field campaigns in August 2023 where we collected and measured variables like macrophyte abundance (species, stem counts, diameters, height), porewater characteristics, and sediment cores. EO played a key role in planning and executing the fieldwork. 

One of the project’s aims is to enhance Finland’s catchment-scale water quality model (WSFS-Vemala) by integrating a macrophyte (blue carbon) module and improving the representation of carbon species and their processes. This update is motivated because boreal lakes differ significantly from the traditional (inorganic) carbonate buffer system: most of the Total Organic Carbon (TOC) is in dissolved form, dissolved organic carbon far exceeds the dissolved inorganic carbon (DOC ≫ DIC), and the chemistry of DOC gives the water additional buffering capacity. The goal of this work is to prepare WSFS-Vemala to deliver upscaled carbon budgets and carbon cycle dynamics, giving water managers tools for anticipating the impacts of land use changes, ecosystem modifications (such as ditching and blue carbon harvesting), or restoration efforts under various climate scenarios. 

EO supports the Blue Lakes analyses in multiple ways. It can provide direct estimates of the extent of blue carbon ecosystems and phenological growth cycles. EO can also provide the diffuse irradiance attenuation coefficient (Kd) to improve light climate inputs for the phytoplankton module. Proxy variables like absorption of Coloured Dissolved Organic Matter (aCDOM) can complement field monitoring when TOC data is not available. 

We will showcase the types of EO data analyzed and incorporated in catchment-scale water quality modelling. We focus on high-resolution instruments such as EU and ESA’s Sentinel-2 and USGS’s Landsat which, under optimal conditions, can deliver dozens of cloud-free scenes for lakes during summer. We also demonstrate the added value of EO by comparing model outcomes before and after the proposed upgrades. 

*Blue Lakes: Digitizing the carbon sink potential of boreal lakes* has received funding from the European Union – NextGenerationEU instrument and is funded by Research Council of Finland, Call: Special RRF funding for research on key areas of green and digital transition (project number: 352811).

:::

### Using Sentinel-2 data to quantify marine traffic in the Archipelago Sea 2018-2024: Where, when and how much?

**Janne Mäyrä¹**, Elina A. Virtanen¹, Markku Viitasalo¹

Afiiliations: Finnish Environment Institute (Syke)

* What: Poster
* Session: [D.02.12 - Big-data Driven AI Techniques in Ocean Applications: Enhancing Marine Monitoring and Analysis](https://lps25.esa.int/programme/programme-session/?id=025B8900-934E-4F1F-B563-A4B6B87DE7549)
* Where: G21

::: {.callout appearance="default" collapse=true}

#### Show abstract

Monitoring and measuring the amount of marine traffic is vital for estimating their effects to marine habitats. Especially recreational boating can cause considerable amounts of pressure locally and threaten habitats formed by submerged aquatic vegetation (SAV). As smaller vessels are able to enter shallow areas, where SAV communities thrive, the increase water turbidity and sedimentation, as well as increase the pollution in these areas through potential gray water discharges. However, while commercial marine traffic has been monitored via the Automatic Identification System (AIS) for a long time, there is a knowledge gap about the trends, amount and local hotspots for recreational boating. Leisure boating is typically measured either through questionnares, logging the visits to harbors, or with visual observations via field work, which, while providing accurate data, have very limited spatial and temporal coverage. Also, while there is a large amount of studies related to marine vessel detection from satellite imagery, most of it is focused on the commercial traffic.

In this study, we used the workflow developed in our earlier research [1] to detect and quantify marine traffic in the Archipelago Sea using Sentinel-2 images. The Archipelago Sea is the largest archipelago in Europe, and the major hub for recreational boating in the Finnish coast. Our study period spans 2018 to 2024, and covers the main period (May-September) for leisure boating in the Finnish Coast for each year. In total, we processed over 1,600 individual Sentinel-2 tiles from 441 timesteps, of which 159 produced suitable results for further analyses. Most of these data were from May, June or July, as only 24 usable images were from August and September. To better quantify especially the recreational marine traffic, we used HELCOM AIS to filter the commercial traffic from our results, as well as to further validate our results.

Based on our results, marine traffic in the Archipelago Sea was concentrated close to the established navigation routes, as the median distance from a route was 135 meters, and 75 % of all detections were less than 600 meters away from the routes. July, the main summer holiday season in Finland, was the most active month each year, and almost half of all detected vessels were from July. Of the observed years, 2022 had the least amount of detected traffic, whereas the two preceding were the most active. These observations correspond with the COVID-19 travel restrictions and when they were lifted in Finland, suggesting that there was a clear surge in recreational boating during the pandemic.

To the best of our knowlegdge, this is the first time that marine traffic including recreational boating has been quantified in this scale in the Archipelago Sea. Our results also show how openly available satellite images coupled with powerful object detection techniques, can support the quantification of recreational boating, without relying on resource-heavy methods (e.g. AIS, high-resolution images). The information can be used to support the development of spatial marine management and conservation measures, and further in ecological research and impact avoidance.

Bibliography:
* Mäyrä, J., Virtanen, E. A., Jokinen, A.-P., Koskikala, J., Väkevä, S., & Attila, J. (2025). Mapping recreational marine traffic from sentinel-2 imagery using Yolo Object Detection Models. Remote Sensing of Environment, 326, 114791. [https://doi.org/10.1016/j.rse.2025.114791](https://doi.org/10.1016/j.rse.2025.114791)

:::

## Thursday 26.6.2025

### Scaling EO Processing Task Scheduling With Compact Representations

**Jesse Anttila¹**, Sakari Väkevä¹, Mikko Kervinen¹, Jenni Attila¹, Yki Laine¹

Affiliations: ¹Finnish Environment Institute (Syke)

* What: Presentation
* Session: [D.04.05 From the Research Lab to a Global Map: Scalable and Sustainable EO Algorithm Development and Workflows](https://lps25.esa.int/programme/programme-session/?id=E08D7F30-6DEF-4574-8B1D-354EC4D3933C)
* Room: Hall L3
* Time: 08:30

::: {.callout appearance="default" collapse=true}

#### Show abstract

The Sampi Workload Scheduler (SWS) is a highly scalable EO processing task scheduler developed at Syke starting from September 2024, with the goal of improving the scalability of Syke's EO processing platform Sampi to allow for hundreds of thousands of simultaneous tasks. Processing tasks are dynamically scheduled to executors in a cloud environment, with rescheduling of interrupted tasks to allow executors to be added and removed freely. SWS uses a highly efficient representation of large processing jobs based on a common structure of EO processing tasks, i.e. a graph of EO processors applied over a number of different inputs. In combination with dynamic provisioning of computation resources and OCI container support, SWS can run very large processing jobs quickly and efficiently with minimal resource overhead and simple integration with existing processing software.

Processing jobs ("Workloads") are represented as a collection of parallel tasks all sharing the same general structure, represented as a graph of EO processors. Each task must have the same processing graph, but may have an unique input value such as a tilename or date. Each vertex of the task graph is an independently schedulable subtask, with the edges representing dependencies between processing steps. This representation allows for arbitrary large processing jobs to represented in constant space, excluding the size of any input values which are stored separately.

The throughput of the scheduling system is primarily limited by the need to persist all changes to processing state in order to be able to recover a globally consistent state at any time. In practice this involves a minimum of two operations for each subtask scheduled and completed. Although the size of the state modified by each operation is minimal, batching and write-ahead logging are required to scale to a throughput of thousands of subtasks completed each second. The state of all active subtasks is cached in memory to avoid the need to perform any reads from persistent storage, requiring around four bytes of memory for each active subtask.

Each cloud VM instance can be used to run several executors simultaneously to maximize resource utilization. Each executor independently requests subtasks, transfers data, runs EO processing software, and reports subtask results. The executors use OCI containers to allow arbitrary processing software to be used without any modifications required to integrate with the scheduling system. The total number of executors and cloud VM instances is scaled according to the number of subtasks available, which helps avoid overprovisioning of compute resources by ensuring that sufficient work is available before scaling up. Underutilized instances can be deprovisioned freely as any interrupted subtasks will be rescheduled to another executor on a different instance.

A set of optimized EO processing software for common tasks in optical EO data processing, including resampling, reprojection, mosaicking and statistics extraction has been created alongside SWS to efficiently utilize the greater scalability enabled by the scheduling system. In particular the data fetching and resampling tool is an order of magniture more efficient than existing solutions for Sentinel-2 and Landsat-8 provided in the SNAP toolkit, with additional features included for area-of-interest masking and cloud detection. These tools significantly reduce the amount of compute time spent on data management tasks, resulting in both speed and cost improvements in EO processing jobs that utilize them.

SWS has been used to compute full mission time-series statistics for Sentinel-2 and Landsat-8/9 for a set of 4896 coastal and lake waterbodies for Water Framework Directive reporting in Finland using two water quality processors, C2RCC and Polymer. The total area is approximately 60 000 km², or 17 megapixels at 60m resolution. The Landsat processing job included 8236 images and had a runtime of 5 hours, with a total of 6400 CPU-hours consumed. At slightly less than one CPU-hour consumed per processed image, the effective per-image processing cost was less than one cent. For the matching Sentinel-2 processing job, 5900 CPU-hours were consumed to process 37320 images, for an effective cost of less than one fifth of a cent per image.

SWS improves on existing container-based scheduling systems like Argo Workflows by introducing the efficient shared graph representation for large processing jobs, which allows for greater scalability while preserving the flexibility of using containerized software. The primary drawback is the inability to represent dynamic processing graphs, preventing the use of loops or conditionals in the graph structure as all processing steps must be known ahead of time. While this is generally the case for large EO processing jobs, a more dynamic solution may be preferable for certain machine learning experiments or ad-hoc processing tasks. With a total memory footprint of less than a hundred megabytes, the scheduling system can be used for processing jobs of any size without any resource allocation scaling.
:::


### Integration of satellite observations to SDG eutrophication indicators in Finnish coastal and lake waterbodies

**Eero Alkio¹**, Laura Hoikkala¹, Jenni Attila¹, Vivi Fleming¹, Sari Mitikka¹, Hanna Alasalmi¹, Vesa Keto¹, Pekka Hurskainen¹

Affiliations: ¹Finnish Environment Institute (Syke)

* What: Presentation
* Session: [F.04.07 Earth Observation for Tracking Global Sustainability and Biodiversity Targets - PART 1](https://lps25.esa.int/programme/programme-session/?id=5B48AB17-286A-4232-B233-4568FD461290)
* Room: Hall F1
* Time: 08:30

::: {.callout appearance="default" collapse=true}

#### Show abstract

The UN global manual on measuring the SDG indicator 14.1.1a, Index of coastal eutrophication, presents three levels of indicators for the goal. Indicators of level 1 are produced by UNEP based on global or globally modelled data, indicators of level 2 are based on national and regional monitoring, and indicators of level 3 are supplementary. Level 2 consists of indicators of chlorophyll-a concentration, national modelling of coastal eutrophication potential, and in situ concentrations of nitrogen, phosphorus, and silica.

Both water sampling data and satellite data are allowable data sources for the level 2 indicators of SDG 14.1.1a (UNEP 2021). The use of satellite data can greatly improve the confidence of the chlorophyll assessment due to its high spatial and temporal coverage. Therefore, we investigate the possibility of including satellite data into the SDG 14.1.1a level 2 chlorophyll-a indicator for Finland’s coastal waters. In order to avoid duplicate work and potentially contrasting results, we use already existing, Syke’s processed water quality datasets, and calculate the coastal zone specific results hierarchically from waterbody specific results; first to water type level and then to the Finnish coastal zone by taking the area weighed average of water type specific results and open sea assessment unit specific results from HELCOM’s chlorophyll-a assessment. Our plan is to merge the beforementioned data into combined, singular indicator value for the Finnish coastal zone.  

Besides UN sustainable development goals (SDG), Syke is involved in other reporting obligations and commitments that Finland has regarding eutrophication status of coastal waters: Descriptor 5 of marine strategy framework directive (MSFD, 2008/56/EC) requires that human-induced eutrophication is minimized, and one of the goals of HELCOM’s Baltic Sea action plan (HELCOM BSAP) is Baltic Sea unaffected by eutrophication. In addition, ecological status assessment of the water framework directive (WFD, 2000/60/EC) is closely related to eutrophication assessment. These established assessments need to be considered when planning the SDG indicators, to avoid duplicate work and contradictions between the different assessments.

During the project, the match between the two data types is analyzed, both visually using the open web map application Tarkka's (tarkka.syke.fi) analysis tool by Finnish Environment Institute (Syke), and with statistical analyses. Tarkka’s analysis tool visualizes satellite observations and station sampling data using various functionalities, such as bars, time series, histograms, and pie charts. In addition, statistical analysis-based correspondence between the two datasets will be explored during the project. Over the coastal water bodies, the match based on visual inspection of the station specific time series between the two datasets was generally good. However, some of the waterbody specific classification results differ between the analyzed data types. This is potentially due to differences in data availability and temporal distribution of the sampling data. 

Furthermore, the satellite data algorithms to interpret chlorophyll-a concentration are under re-development cycle which is estimated to be complete in the end of year 2024. Hence, a more refined and accurate chlorophyll-a satellite dataset will be available for visual and statistical analysis. Data-analysis with this refined, new dataset is likely to provide more insights regarding the pivotal implementation of EO-data into the level 2 SDG 14.1.1a indicator. 

In our presentation we will give an overview of the EO data provided for the SDG indicator development, a validation analysis between EO and in-situ datasets, and how EO data could complement and improve the previously reported SGD indicator results.

:::

### Tarkka: A Comprehensive EO Service for Environmental Monitoring and Policy Support

**Hanna Alasalmi¹**, Vesa Keto¹, Jenni Attila¹, Sampsa Koponen¹, Mikko Kervinen¹, Eeva Bruun¹, Sakari Väkevä¹, Kirsikka Heinilä¹, Timo Pyhälahti¹, Jesse Anttila¹, Eero Alkio¹, Yki Laine¹

Affiliations: ¹ Finnish Environment Institute (Syke)

* What: Poster
* Session: [D.05.01 - Showcasing EO Data and Information Services](https://lps25.esa.int/programme/programme-session/?id=90B14AEE-5466-4A04-8728-82BD35C7A882)
* Where: V10

::: {.callout appearance="default" collapse=true}

#### Show abstract

Earth Observation provides valuable information about the status of the environment, sources of pollution and biodiversity to support various EU, regional, and national policies and directives. These include EU’s Integrated Maritime Policy, maritime spatial planning, the Water Framework and Marine Strategy Framework Directives, the Nature Restoration Law, and – on a regional level – the Helsinki Convention (HELCOM).

Providing convenient access to Earth Observation (EO) materials, along with GIS, model, and in situ data, is essential for expanding the use of satellite data. Since 2017, the Finnish Environment Institute (Syke) has been offering the EO service Tarkka [tarkka.syke.fi](tarkka.syke.fi), a web application that provides users with both satellite and in situ data and tools for visualization. Due to its popularity, a next generation of the service was launched in 2022. Tarkka is built on open-source solutions and leverages Syke’s open data offerings. The water quality data provided by Syke’s services cover Baltic Sea region, especially Finnish coastal areas and lakes. Although cloud cover often obstructs useful observations, the amount of data available is still substantial. The development of Tarkka has focused on user experience, aiming to provide easier access to cloudless observations from a large amount of data.

Tarkka includes a continuously expanding list of EO datasets and has also integrated in-situ data from monitoring stations, automated stations, citizen observations, and ships (FerryBox), as well as modeled data and related GIS data. This information is presented as maps, image galleries, and regional data in statistical time series. To meet user needs, such as those for the Water Framework Directive purposes for regional datasets, an advanced analysis tool has been developed to visualize the statistical datasets of EO and station sampling data. The analysis tools include various functionalities such as time series, histograms, pie charts, and more.

ESA has supported this activity by providing funding (under the EO4society programme) through the BalticAIMS project ([www.syke.fi/projects/BalticAIMS, contract number 4000133565/20/I-NB](www.syke.fi/projects/BalticAIMS)). The goal of the 1st funding period (2021-2023) was to demonstrate an integrated data approach for essential processes of land and coastal water areas to better analyze and visualize the interactions. In fall 2024 the project was extended for 18 months with a goal of further improving the services and the data it provides. 

The presentation will demonstrate the latest tools and capabilities available in Tarkka for use cases related to monitoring the status of the environment for directives and Maritime Spatial Planning.

::: 

### Lake Ice Monitoring as a Climate Service: Integrating Earth Observation and Stakeholder Feedback

**Kirsikka Heinilä¹**, Sari Metsämäki¹, Sakari Väkevä¹, Hanna Alasalmi¹, Timo Pyhälahti¹, Jesse Anttila¹, Kari Luojus², Gabriele Schwaizer³

Affiliations: ¹Finnish Environment Institute (Syke) ²Finnish Meteorological Institute ³ENVEO IT Gmbh

* What: Poster
* Session: [A.05.02 - Earth observation for Climate Services](https://lps25.esa.int/programme/programme-session/?id=86A896F5-3E68-41F9-8E24-C6DF4C2431E9)
* Where: C19

::: {.callout appearance="default" collapse=true}

#### Show abstract

Monitoring lake ice cover is vital for understanding, protecting, and managing freshwater ecosystems, as well as ensuring safety and transportation in regions with seasonal ice cover. Importantly, as recognized as an Essential Climate Variable (ECV), lake ice provides critical information for advancing climate services and understanding climate change impacts due to its sensitivity to temperature fluctuations and trends. Significant changes in lake ice dynamics have already been observed in northern latitudes, with even more pronounced impacts predicted as the climate warms.

Earth Observation (EO) data provides a unique opportunity to monitor lake ice conditions at spatial and temporal scales previously inaccessible. The Copernicus program delivers near-real-time satellite data that underpins both scientific research and practical applications, offering critical insights into regional and global lake ice dynamics. These products not only support regional and global lake ice dynamics studies but also contribute to Essential Climate Variable (ECV) datasets, which are foundational for advancing EO-based climate services. Starting in 2025, Copernicus will expand its medium-resolution (500 m) daily lake ice data from the Northern Hemisphere to include the Southern Hemisphere within its Copernicus Land Monitoring Service portfolio. This product, produced collaboratively with the cryosphere team comprising the Finnish Environment Institute (Syke), the Finnish Meteorological Institute (FMI), and ENVEO, is based on the ICEmod method developed by the Syke. It exploits Sentinel-3 Land Surface Temperature Radiometer (SLSTR) data to assess lake ice extent while integrating cloud detection as part of the classification process. Additionally, the high-resolution lake ice products under the Pan-European Copernicus Water, Snow, and Ice (HR-WSI) initiative are undergoing quality improvements, with Syke and the NORCE Norwegian Research Centre conducting extensive independent validation during spring 2025.

Through the Horizon 2020 Arctic PASSION project, Syke has developed the Lake Ice Service, a comprehensive climate service that integrates satellite-based products, true-color imagery, and ground-based observations into user-friendly tools. Designed in collaboration with stakeholders—including local communities, researchers, and hydropower operators—the service addresses diverse user needs through co-production workshops, interviews, and feedback mechanisms. The increasing urgency of climate change and its profound impact on seasonal ice conditions drive both Indigenous communities and researchers to seek actionable lake ice data to adapt to and mitigate these rapidly changing environmental conditions. Key innovations include the Highlighting Interesting Phenomena (HISP) tool, which enables users to annotate satellite images with reports of unusual ice conditions, contributing to a shared database of local knowledge. A mobile application under development will also allow offline reporting, addressing the connectivity challenges of Arctic regions.

By integrating state-of-the-art EO technologies with stakeholder-driven design, the Lake Ice Service exemplifies how EO-based climate services can bridge the gap between scientific knowledge and actionable insights for decision-making. This presentation will focus on showcasing the development of the lake ice service and Copernicus lake ice products, highlighting their important role in supporting EO-based climate services and their contribution to advancing global climate services

:::

### Validation of Copernicus High Resolution Snow Products

**Sari Metsämäki¹**, Eirik Malnes, Sakari Väkevä, Hannah Vickers, Kirsikka Heinilä, Jesse Anttila

Affiliations: ¹Finnish Environment Institute (Syke) ²NORCE Norwegian Research Centre

* What: Poster
* Session: [A.05.02 - Earth observation for Climate Services](https://lps25.esa.int/programme/programme-session/?id=86A896F5-3E68-41F9-8E24-C6DF4C2431E9)
* Where: C20

::: {.callout appearance="default" collapse=true}

#### Show abstract

The Pan-European high-resolution Water, Snow, and Ice products, collectively known as HR-WSI are provided under Copernicus Land Monitoring Service (CLMS). The service provides various Sentinel-1 and Sentinel-2-derived products at high spatial resolutions, down to 10 m to 20 m. The European Environment Agency (EEA) contracted the production of these datasets for 2024–2025. Because of planned methodological changes, the call also included external review and validation tasks as a separate part of the contract. A consortium team formed by Finnish Environment Institute (Syke) and NORCE Norwegian Research Centre was chosen to conduct this work. Here we present the independent validation results of HRWSI snow products, particularly focusing on Fractional Snow Cover, which underwent changes still during the validation process, and will therefore be revalidated during the spring 2025. The validation is of fundamental importance for the Copernicus user community, given that these products may be exploited in several applications such as hydrological modeling, avalanche and flood warnings, hydropower industry, tourism, etc.
 
The Fractional Snow Cover product portfolio consist of three products:  daily Fractional Snow Cover on Ground and on Top of Canopy (FSCOG and FSCTOC) and 7-day aggregated gap-filled FSC (GFSC). The FSCTOC and FSCOG are based on optical S-2 observations, while GFSC also utilizes S-1 based snow information. The Snow Phenology (SP) product consist of Snow Cover Onset (SCO) Snow Cover Melt (SCM) and Snow Cover Duration (SCD) and is based both on S-1 and S-2 data. To account for the regional differences and diversity of European landscape, topography, climate and snow regimes, 16 Sentinel-2 tiles were chosen in different parts of Europe. Validation is conducted for the hydrological year October 2020-September 2021. 
 
The validation benefits from Syke and NORCE's extensive experiences with remote sensing and in situ observations and models.  In overall validation of FSCOG, synoptic weather station network data from World Meteorological Organization (WMO) are exploited, including air temperature, ground status, and snow depth. As an important addition, in situ observations from Finland's snow course network, and the Norwegian snow depth and profiling activities arere used. 
 
For some variables, such as the wet/dry snow classification of snowpack and snow phenology, comprehensive in situ validation datasets are not available for all regions. Therefore, European-wide snow model for variables like liquid water content and snow cover were developed independently. These data were subsequently verified by comparing them with operational hydrological models such as the Norwegian snow model (seNorge) and Syke's operational hydrological forecasting system (WSFS). For FSCTOC the independent reference snow maps also based on S-2 observations are utilized. At times, validation of FSCOG and FSCTOC is performed using visual assessment of EO products with expert judgment. 

Validation results are presented in several ways. An overall validation for FSCOG relies on Snow Depth observations made at Weather Stations, by first classifying both FSCOG and Snow Depth to snow/non-snow information. Then several statistical binary metrics like Recall, F-score and False Alarm Rate are calculated. In addition to this point-wise method, also pixel-to-pixel comparison is made for some of the tiles, using independent reference FSCTOC maps provided as courtesy of ENVEO IT GmbH. This results in RMSE and Bias. The validation results for Snow Phenology and GFSC are based on the comparison of the developed snow model data: the evaluation of the product is based on the comparison of time series from the model and the snow product. Also, conclusions from visual assessment are presented, accompanied with explanatory figures. 
 


:::